/*
 * NewJFrame.java
 *
 * Created on 19 de diciembre de 2007, 21:08
 */

package Gui;

import Reportes.ReporteCubierto;
import Reportes.ReporteRanking;
import Reportes.ReporteTotales;
import base.Empresa;
import base.Socio;
import db.DbRepRanking;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Witzkito
 */
public class V_Estadistica extends javax.swing.JFrame {
    
    private Empresa emp;
    DecimalFormat dcf;
    /** Creates new form NewJFrame */
    public V_Estadistica(Empresa emp) {
        this.emp = emp;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        dcf = new DecimalFormat("###,###,###");
        load();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttGroupRanking = new javax.swing.ButtonGroup();
        bttGroupCiclo = new javax.swing.ButtonGroup();
        pnlDatos = new javax.swing.JPanel();
        pnlDatos.setBorder(BorderFactory.createTitledBorder("Datos"));
        jLabel1 = new javax.swing.JLabel();
        txtTemporada = new javax.swing.JTextField();
        Calendar cal = Calendar.getInstance();
        txtTemporada.setText(String.valueOf("Temporada " + (cal.get(Calendar.YEAR))));
        bttArriba = new javax.swing.JButton();
        bttAbajo = new javax.swing.JButton();
        bttAbajo1 = new javax.swing.JButton();
        kg1AñoP = new javax.swing.JLabel();
        kg1AñoP1 = new javax.swing.JLabel();
        tblPane = new javax.swing.JTabbedPane();
        tbpTotales = new javax.swing.JPanel();
        Total1KgP = new javax.swing.JLabel();
        lblTotal1KgP = new javax.swing.JLabel();
        lblTotal2kgP = new javax.swing.JLabel();
        Total1KgP1 = new javax.swing.JLabel();
        lblTotal1kgE = new javax.swing.JLabel();
        lblTotal2kgE = new javax.swing.JLabel();
        bttListar = new javax.swing.JButton();
        Total1KgP3 = new javax.swing.JLabel();
        lbl1Año = new javax.swing.JLabel();
        lbl2Año = new javax.swing.JLabel();
        lblCensoPlantacion = new javax.swing.JLabel();
        lblTotalCensoPlantacion = new javax.swing.JLabel();
        lbl1Año1 = new javax.swing.JLabel();
        lbl2Año1 = new javax.swing.JLabel();
        lblCensoPlantacion1 = new javax.swing.JLabel();
        lblTotalKgCEntrega = new javax.swing.JLabel();
        lbl1Año2 = new javax.swing.JLabel();
        lblTotalEnt1Año = new javax.swing.JLabel();
        lbl2Año2 = new javax.swing.JLabel();
        lblTotalEnt2Año = new javax.swing.JLabel();
        lblCensoPlantacion2 = new javax.swing.JLabel();
        lblTotalEntrega = new javax.swing.JLabel();
        tbpCubierto = new javax.swing.JPanel();
        lblCubierto = new javax.swing.JLabel();
        cmbCubierto = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Vector colNames = new Vector(3);
        colNames.add("Numero");
        colNames.add("Nombre");
        colNames.add("Hectareas");
        Vector rows = new Vector();
        V_Tabla tabla = new V_Tabla(rows,colNames);
        tblListadoCub = new JTable(tabla);
        bttListar1 = new javax.swing.JButton();
        jPnlRanking = new javax.swing.JPanel();
        chkTodos = new javax.swing.JCheckBox();
        rdCensoPlantacion = new javax.swing.JRadioButton();
        rdCensoEntrega = new javax.swing.JRadioButton();
        rdEntrega = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        colNames = new Vector(4);
        colNames.add("Puesto");
        colNames.add("Numero");
        colNames.add("Nombre");
        colNames.add("Total");
        rows = new Vector();
        tabla = new V_Tabla(rows,colNames);
        tblListadoRanking = new JTable(tabla);
        bttListarRanking = new javax.swing.JButton();
        rdTodosCiclos = new javax.swing.JRadioButton();
        rdCiclo1 = new javax.swing.JRadioButton();
        rdCiclo2 = new javax.swing.JRadioButton();
        pnlAcciones = new javax.swing.JPanel();
        bttAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadistica");
        setBackground(this.emp.getOptions().getColor_form());
        setIconImage(this.emp.getOptions().getIcono().getImage());

        pnlDatos.setBackground(this.emp.getOptions().getColor_form());
        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setFont(this.emp.getOptions().getFontLbl());
        jLabel1.setText("Temporada");

        txtTemporada.setEditable(false);
        txtTemporada.setFont(this.emp.getOptions().getFontTxt());

        bttArriba.setIcon(new ImageIcon("img/fleArriba.gif"));
        bttArriba.setMinimumSize(new java.awt.Dimension(15, 10));
        bttArriba.setPreferredSize(new java.awt.Dimension(15, 10));
        bttArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttArriba_Click(evt);
            }
        });

        bttAbajo.setIcon(new ImageIcon("img/fleAbajo.gif"));
        bttAbajo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bttAbajo.setMinimumSize(new java.awt.Dimension(15, 10));
        bttAbajo.setPreferredSize(new java.awt.Dimension(15, 10));
        bttAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAbajo_Click(evt);
            }
        });

        bttAbajo1.setIcon(new ImageIcon("img/fleAbajo.gif"));
        bttAbajo1.setMinimumSize(new java.awt.Dimension(15, 10));
        bttAbajo1.setPreferredSize(new java.awt.Dimension(15, 10));

        kg1AñoP.setFont(this.emp.getOptions().getFontLbl());

        kg1AñoP1.setFont(this.emp.getOptions().getFontLbl());

        tblPane.setName("Totales"); // NOI18N

        tbpTotales.setBackground(this.emp.getOptions().getColor_form());
        tbpTotales.setName("Totales"); // NOI18N

        Total1KgP.setFont(this.emp.getOptions().getFontLbl());
        Total1KgP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total1KgP.setText("Censo Plantacion");
        Total1KgP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblTotal1KgP.setFont(this.emp.getOptions().getFontLbl());
        lblTotal1KgP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal1KgP.setText("Temporada");

        lblTotal2kgP.setFont(this.emp.getOptions().getFontLbl());
        lblTotal2kgP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal2kgP.setText("Temporada");

        Total1KgP1.setFont(this.emp.getOptions().getFontLbl());
        Total1KgP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total1KgP1.setText("Censo Entrega");
        Total1KgP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblTotal1kgE.setFont(this.emp.getOptions().getFontLbl());
        lblTotal1kgE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal1kgE.setText("Temporada");

        lblTotal2kgE.setFont(this.emp.getOptions().getFontLbl());
        lblTotal2kgE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal2kgE.setText("Temporada");

        bttListar.setIcon(new ImageIcon("img/listado.png"));
        bttListar.setText("Listar");
        bttListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListar_Click(evt);
            }
        });

        Total1KgP3.setFont(this.emp.getOptions().getFontLbl());
        Total1KgP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total1KgP3.setText("Total Entrega");
        Total1KgP3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl1Año.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl1Año.setText("1 Año:");

        lbl2Año.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl2Año.setText("2 Año:");

        lblCensoPlantacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCensoPlantacion.setText("Total:");

        lblTotalCensoPlantacion.setFont(this.emp.getOptions().getFontLbl());
        lblTotalCensoPlantacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalCensoPlantacion.setText("Temporada");

        lbl1Año1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl1Año1.setText("1 Año:");

        lbl2Año1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl2Año1.setText("2 Año:");

        lblCensoPlantacion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCensoPlantacion1.setText("Total:");

        lblTotalKgCEntrega.setFont(this.emp.getOptions().getFontLbl());
        lblTotalKgCEntrega.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalKgCEntrega.setText("Temporada");

        lbl1Año2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl1Año2.setText("1 Año:");

        lblTotalEnt1Año.setFont(this.emp.getOptions().getFontLbl());
        lblTotalEnt1Año.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalEnt1Año.setText("Temporada");

        lbl2Año2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl2Año2.setText("2 Año:");

        lblTotalEnt2Año.setFont(this.emp.getOptions().getFontLbl());
        lblTotalEnt2Año.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalEnt2Año.setText("Temporada");

        lblCensoPlantacion2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCensoPlantacion2.setText("Total:");

        lblTotalEntrega.setFont(this.emp.getOptions().getFontLbl());
        lblTotalEntrega.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalEntrega.setText("Temporada");

        javax.swing.GroupLayout tbpTotalesLayout = new javax.swing.GroupLayout(tbpTotales);
        tbpTotales.setLayout(tbpTotalesLayout);
        tbpTotalesLayout.setHorizontalGroup(
            tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbpTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Total1KgP, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbpTotalesLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCensoPlantacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl2Año, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl1Año, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalCensoPlantacion, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(lblTotal2kgP, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(lblTotal1KgP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(tbpTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Total1KgP1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbpTotalesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl2Año1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl1Año1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(lblCensoPlantacion1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotalKgCEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal2kgE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal1kgE, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(tbpTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbpTotalesLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(bttListar)
                        .addGap(139, 139, 139))
                    .addComponent(Total1KgP3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbpTotalesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl2Año2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl1Año2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(lblCensoPlantacion2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotalEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalEnt2Año, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalEnt1Año, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        tbpTotalesLayout.setVerticalGroup(
            tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbpTotalesLayout.createSequentialGroup()
                .addComponent(Total1KgP)
                .addGap(9, 9, 9)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1Año)
                    .addComponent(lblTotal1KgP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2Año)
                    .addComponent(lblTotal2kgP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCensoPlantacion)
                    .addComponent(lblTotalCensoPlantacion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total1KgP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal1kgE)
                    .addComponent(lbl1Año1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal2kgE)
                    .addComponent(lbl2Año1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCensoPlantacion1)
                    .addComponent(lblTotalKgCEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total1KgP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalEnt1Año)
                    .addComponent(lbl1Año2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalEnt2Año)
                    .addComponent(lbl2Año2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCensoPlantacion2)
                    .addComponent(lblTotalEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(bttListar)
                .addGap(43, 43, 43))
        );

        tblPane.addTab("Totales", tbpTotales);

        tbpCubierto.setBackground(this.emp.getOptions().getColor_form());

        lblCubierto.setFont(this.emp.getOptions().getFontLbl());
        lblCubierto.setText("Cubierto");

        cmbCubierto.setFont(this.emp.getOptions().getFontLbl());
        cmbCubierto.setMinimumSize(new java.awt.Dimension(23, 16));
        cmbCubierto.setPreferredSize(new java.awt.Dimension(28, 18));
        cmbCubierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCubierto_Click(evt);
            }
        });

        TableRender render = new TableRender();
        tblListadoCub.setDefaultRenderer(String.class, render);
        tblListadoCub.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblListadoCub.getColumnModel().getColumn(1).setPreferredWidth(180);
        tblListadoCub.getColumnModel().getColumn(2).setPreferredWidth(50);
        jScrollPane1.setViewportView(tblListadoCub);

        bttListar1.setIcon(new ImageIcon("img/listado.png"));
        bttListar1.setText("Listar");
        bttListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListarCubierto_Click(evt);
            }
        });

        javax.swing.GroupLayout tbpCubiertoLayout = new javax.swing.GroupLayout(tbpCubierto);
        tbpCubierto.setLayout(tbpCubiertoLayout);
        tbpCubiertoLayout.setHorizontalGroup(
            tbpCubiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbpCubiertoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tbpCubiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(tbpCubiertoLayout.createSequentialGroup()
                        .addComponent(lblCubierto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCubierto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(bttListar1))
                .addGap(21, 21, 21))
        );
        tbpCubiertoLayout.setVerticalGroup(
            tbpCubiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbpCubiertoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tbpCubiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCubierto)
                    .addComponent(cmbCubierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttListar1)
                .addGap(23, 23, 23))
        );

        tblPane.addTab("Cubierto", tbpCubierto);

        jPnlRanking.setBackground(this.emp.getOptions().getColor_form());

        chkTodos.setBackground(this.emp.getOptions().getColor_form());
        chkTodos.setFont(this.emp.getOptions().getFontLbl());
        chkTodos.setText("Todas las temporadas");
        chkTodos.setToolTipText("El ranking se calcula con todas las temporadas");
        chkTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTodosActionPerformed(evt);
            }
        });

        rdCensoPlantacion.setBackground(this.emp.getOptions().getColor_form());
        bttGroupRanking.add(rdCensoPlantacion);
        rdCensoPlantacion.setFont(this.emp.getOptions().getFontLbl());
        rdCensoPlantacion.setText("Censo Plantacion");
        rdCensoPlantacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCensoPlantacion_Click(evt);
            }
        });

        rdCensoEntrega.setBackground(this.emp.getOptions().getColor_form());
        bttGroupRanking.add(rdCensoEntrega);
        rdCensoEntrega.setFont(this.emp.getOptions().getFontLbl());
        rdCensoEntrega.setText("Censo Entrega");
        rdCensoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCensoEntregaActionPerformed(evt);
            }
        });

        rdEntrega.setBackground(this.emp.getOptions().getColor_form());
        bttGroupRanking.add(rdEntrega);
        rdEntrega.setFont(this.emp.getOptions().getFontLbl());
        rdEntrega.setText("Entrega");
        rdEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEntregaActionPerformed(evt);
            }
        });

        render = new TableRender();
        tblListadoRanking.setDefaultRenderer(String.class, render);
        tblListadoRanking.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblListadoRanking.getColumnModel().getColumn(1).setPreferredWidth(20);
        tblListadoRanking.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblListadoRanking.getColumnModel().getColumn(3).setPreferredWidth(50);
        jScrollPane2.setViewportView(tblListadoRanking);

        bttListarRanking.setIcon(new ImageIcon("img/listado.png"));
        bttListarRanking.setText("Listar");
        bttListarRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListarRanking_Click(evt);
            }
        });

        rdTodosCiclos.setBackground(this.emp.getOptions().getColor_form());
        bttGroupCiclo.add(rdTodosCiclos);
        rdTodosCiclos.setFont(this.emp.getOptions().getFontLbl());
        rdTodosCiclos.setSelected(true);
        rdTodosCiclos.setText("Todos los Ciclos");
        rdTodosCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTodosCiclosActionPerformed(evt);
            }
        });

        rdCiclo1.setBackground(this.emp.getOptions().getColor_form());
        bttGroupCiclo.add(rdCiclo1);
        rdCiclo1.setFont(this.emp.getOptions().getFontLbl());
        rdCiclo1.setText("1 Año");
        rdCiclo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCiclo1ActionPerformed(evt);
            }
        });

        rdCiclo2.setBackground(this.emp.getOptions().getColor_form());
        bttGroupCiclo.add(rdCiclo2);
        rdCiclo2.setFont(this.emp.getOptions().getFontLbl());
        rdCiclo2.setText("2 Años");
        rdCiclo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCiclo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlRankingLayout = new javax.swing.GroupLayout(jPnlRanking);
        jPnlRanking.setLayout(jPnlRankingLayout);
        jPnlRankingLayout.setHorizontalGroup(
            jPnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlRankingLayout.createSequentialGroup()
                .addGroup(jPnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlRankingLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(chkTodos))
                    .addGroup(jPnlRankingLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdTodosCiclos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdCensoPlantacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(jPnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdCiclo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdCensoEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdCiclo2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(rdEntrega))))
                .addContainerGap(25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPnlRankingLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(bttListarRanking)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(jPnlRankingLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPnlRankingLayout.setVerticalGroup(
            jPnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlRankingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdCensoEntrega)
                    .addComponent(rdEntrega)
                    .addComponent(rdCensoPlantacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdTodosCiclos)
                    .addComponent(rdCiclo1)
                    .addComponent(rdCiclo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttListarRanking)
                .addContainerGap())
        );

        tblPane.addTab("Ranking", jPnlRanking);

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(kg1AñoP)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addComponent(tblPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 360, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 360, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                    .addContainerGap(202, Short.MAX_VALUE)
                    .addComponent(kg1AñoP1)
                    .addGap(158, 158, 158)))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 360, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 360, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 360, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 360, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bttArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(bttAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblPane, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kg1AñoP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 430, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 430, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDatosLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(kg1AñoP1)
                    .addContainerGap(346, Short.MAX_VALUE)))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 430, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 430, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 430, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        pnlAcciones.setBackground(this.emp.getOptions().getColor_form());
        pnlAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        bttAceptar.setIcon(new ImageIcon("img/Ok.png"));
        bttAceptar.setText("Aceptar");
        bttAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAceptar_Click(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(bttAceptar)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttAceptar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttArriba_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttArriba_Click
        String temporada = txtTemporada.getText().replace("Temporada ", "");
        txtTemporada.setText(String.valueOf("Temporada " + (new Integer(temporada) + 1)));
        temporada = txtTemporada.getText().replace("Temporada ", "");
       lblTotal1KgP.setText(String.valueOf(new Double(this.emp.getTotal1Hec(temporada)).longValue() +
                " Hectareas " + dcf.format(new Double(this.emp.getTotal1KgCensoP(temporada)).longValue()) + " Kg"));
        lblTotal2kgP.setText(String.valueOf(new Double(this.emp.getTotal2Hec(temporada)).longValue() +
                 " Hectareas " + dcf.format(new Double(this.emp.getTotal2KgCensoP(temporada)).longValue()) + " Kg"));
        lblTotalCensoPlantacion.setText(String.valueOf(new Double(this.emp.getTotal1Hec(temporada) +
                this.emp.getTotal2Hec(temporada)).longValue() + " Hectareas " +
                dcf.format(new Double(this.emp.getTotal1KgCensoP(temporada) + this.emp.getTotal2KgCensoP(temporada)).longValue()) +
                " Kg"));
        lblTotal1kgE.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1KgCensoEntrega(temporada)).longValue()) +
                " Kg " ));
        lblTotal2kgE.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal2KgCensoEntrega(temporada)).longValue()) +
                 " Kg "));
        lblTotalKgCEntrega.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1KgCensoEntrega(temporada) +
                this.emp.getTotal2KgCensoEntrega(temporada)).longValue()) + " Kg"));
        lblTotalEnt1Año.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1AñoEntrega(temporada)).longValue())) + " Kg");
        lblTotalEnt2Año.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal2AñoEntrega(temporada)).longValue())) + " Kg");
        lblTotalEntrega.setText(String.valueOf(dcf.format(new Double(this.emp.getTotalEntrega(temporada)).longValue())) + " Kg");
        cargarCmbCubierto(this.emp.getCubierto(temporada));
    }//GEN-LAST:event_bttArriba_Click

    private void bttAbajo_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAbajo_Click
        String temporada = txtTemporada.getText().replace("Temporada ", "");
        txtTemporada.setText(String.valueOf("Temporada " + (new Integer(temporada) - 1)));
        temporada = txtTemporada.getText().replace("Temporada ", "");        
        lblTotal1KgP.setText(String.valueOf(new Double(this.emp.getTotal1Hec(temporada)).longValue() +
                " Hectareas " + dcf.format(new Double(this.emp.getTotal1KgCensoP(temporada)).longValue()) + " Kg"));
        lblTotal2kgP.setText(String.valueOf(new Double(this.emp.getTotal2Hec(temporada)).longValue() +
                 " Hectareas " + dcf.format(new Double(this.emp.getTotal2KgCensoP(temporada)).longValue()) + " Kg"));
        lblTotalCensoPlantacion.setText(String.valueOf(new Double(this.emp.getTotal1Hec(temporada) +
                this.emp.getTotal2Hec(temporada)).longValue() + " Hectareas " +
                dcf.format(new Double(this.emp.getTotal1KgCensoP(temporada) + this.emp.getTotal2KgCensoP(temporada)).longValue()) +
                " Kg"));
        lblTotal1kgE.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1KgCensoEntrega(temporada)).longValue()) +
                " Kg " ));
        lblTotal2kgE.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal2KgCensoEntrega(temporada)).longValue()) +
                 " Kg "));
        lblTotalKgCEntrega.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1KgCensoEntrega(temporada) +
                this.emp.getTotal2KgCensoEntrega(temporada)).longValue()) + " Kg"));
        lblTotalEnt1Año.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1AñoEntrega(temporada)).longValue())) + " Kg");
        lblTotalEnt2Año.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal2AñoEntrega(temporada)).longValue())) + " Kg");
        lblTotalEntrega.setText(String.valueOf(dcf.format(new Double(this.emp.getTotalEntrega(temporada)).longValue())) + " Kg");
        cargarCmbCubierto(this.emp.getCubierto(temporada));
    }//GEN-LAST:event_bttAbajo_Click

    private void bttAceptar_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAceptar_Click
        this.dispose();
    }//GEN-LAST:event_bttAceptar_Click

    private void bttListar_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttListar_Click
        String temporada = txtTemporada.getText().replace("Temporada ", "");
        ReporteTotales rep = new ReporteTotales(this.emp, temporada, "Totales",
                this.emp.getTotal1Hec(temporada),emp.getTotal2Hec(temporada),
                this.emp.getTotal1KgCensoP(temporada), this.emp.getTotal2KgCensoP(temporada),
                this.emp.getTotal1KgCensoEntrega(temporada), this.emp.getTotal2KgCensoEntrega(temporada),
                this.emp.getTotal1AñoEntrega(temporada), this.emp.getTotal2AñoEntrega(temporada),
                this.emp.getTotal1Hec(temporada) + this.emp.getTotal2Hec(temporada),
                this.emp.getTotal1KgCensoP(temporada) + this.emp.getTotal2KgCensoP(temporada),
                this.emp.getTotal1KgCensoEntrega(temporada) + this.emp.getTotal2KgCensoEntrega(temporada),
                this.emp.getTotal1AñoEntrega(temporada), this.emp.getTotal2AñoEntrega(temporada),
                this.emp.getTotalEntrega(temporada));
        rep.run();
    }//GEN-LAST:event_bttListar_Click

    private void bttListarCubierto_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttListarCubierto_Click
        String temporada = txtTemporada.getText().replace("Temporada ", "");
        double cubierto = (Double)cmbCubierto.getSelectedItem();
        ReporteCubierto rep = new ReporteCubierto(this.emp,temporada,cubierto, "Listado Cubierto");
        rep.run();//GEN-LAST:event_bttListarCubierto_Click
}

    private void cmbCubierto_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCubierto_Click
        String temporada = txtTemporada.getText().replace("Temporada ", "");
        if (cmbCubierto.getSelectedItem() != null){
            double numero = (Double)cmbCubierto.getSelectedItem();
            llenarTabla(this.emp.getSocios(temporada, numero));
           
        }
    }//GEN-LAST:event_cmbCubierto_Click

    private void chkTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTodosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkTodosActionPerformed

    private void bttListarRanking_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttListarRanking_Click
        DbRepRanking db = new DbRepRanking(Empresa.con); ReporteRanking rep;
        db.borrarAll();
        int cont = tblListadoRanking.getRowCount();
        while (cont != 0){
            db.Insert(String.valueOf((tblListadoRanking.getModel()).getValueAt(cont - 1, 1)),
                    String.valueOf((tblListadoRanking.getModel()).getValueAt(cont - 1, 2)),
                    String.valueOf((tblListadoRanking.getModel()).getValueAt(cont - 1, 3)),
                    String.valueOf((tblListadoRanking.getModel()).getValueAt(cont - 1, 0)));
            cont = cont - 1;
        }
        if (this.chkTodos.isSelected()){
            if (this.rdCensoPlantacion.isSelected()){
                 rep = new ReporteRanking(this.emp,"Ranking Censo Plantacion " + this.getRdNombreReporte(), " ");
            }else if (this.rdCensoEntrega.isSelected()){
                 rep = new ReporteRanking(this.emp,"Ranking Censo Entrega " + this.getRdNombreReporte(), " ");
            }else{
                rep = new ReporteRanking(this.emp, "Ranking Entrega " + this.getRdNombreReporte(), " ");
            }
        }else{
            String temporada = txtTemporada.getText().replace("Temporada ", "");
            if (this.rdCensoPlantacion.isSelected()){
                 rep = new ReporteRanking(this.emp,"Ranking Censo Plantacion " + this.getRdNombreReporte(), temporada);
            }else if (this.rdCensoEntrega.isSelected()){
                 rep = new ReporteRanking(this.emp,"Ranking Censo Entrega " + this.getRdNombreReporte(), temporada);
            }else{
                rep = new ReporteRanking(this.emp, "Ranking Entrega " + this.getRdNombreReporte(), temporada);
            }
        }
        rep.run();
        
}//GEN-LAST:event_bttListarRanking_Click

    private void rdCensoPlantacion_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCensoPlantacion_Click
        if (chkTodos.isSelected()){
            llenarTablaRanking(this.emp.getRankingCensoPlantacionAll(this.getRdNombreCiclo()), " ", "censo plantacion");
        }else{
            String temporada = txtTemporada.getText().replace("Temporada ", "");
            llenarTablaRanking(this.emp.getRankingCensoPlantacion(temporada, this.getRdNombreCiclo()), temporada,"censo plantacion");
        }
    }//GEN-LAST:event_rdCensoPlantacion_Click

    private void rdCensoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCensoEntregaActionPerformed
        if (chkTodos.isSelected()){
            llenarTablaRanking(this.emp.getRankingCensoEntregaAll(this.getRdNombreCiclo()), " ", "censo entrega");
        }else{
            String temporada = txtTemporada.getText().replace("Temporada ", "");
            llenarTablaRanking(this.emp.getRankingCensoEntrega(temporada, this.getRdNombreCiclo()), temporada, "censo entrega");
        }
    }//GEN-LAST:event_rdCensoEntregaActionPerformed

    private void rdEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEntregaActionPerformed
        if (chkTodos.isSelected()){
            llenarTablaRanking(this.emp.getRankingEntregaAll(this.getRdNombreCiclo()), " ", "entrega");
        }else{
            String temporada = txtTemporada.getText().replace("Temporada ","");
            llenarTablaRanking(this.emp.getRankingEntrega(temporada, this.getRdNombreCiclo()), temporada, "entrega");
        }
    }//GEN-LAST:event_rdEntregaActionPerformed

    private void rdTodosCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTodosCiclosActionPerformed
        if (this.rdEntrega.isSelected()){
            this.rdEntregaActionPerformed(evt);
        }else if (this.rdCensoEntrega.isSelected()){
            this.rdCensoEntregaActionPerformed(evt);
        }else if (this.rdCensoPlantacion.isSelected()){
            this.rdCensoPlantacion_Click(evt);
        }
    }//GEN-LAST:event_rdTodosCiclosActionPerformed

    private void rdCiclo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCiclo1ActionPerformed
        if (this.rdEntrega.isSelected()){
            this.rdEntregaActionPerformed(evt);
        }else if (this.rdCensoEntrega.isSelected()){
            this.rdCensoEntregaActionPerformed(evt);
        }else if (this.rdCensoPlantacion.isSelected()){
            this.rdCensoPlantacion_Click(evt);
        }
    }//GEN-LAST:event_rdCiclo1ActionPerformed

    private void rdCiclo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCiclo2ActionPerformed
        if (this.rdEntrega.isSelected()){
            this.rdEntregaActionPerformed(evt);
        }else if (this.rdCensoEntrega.isSelected()){
            this.rdCensoEntregaActionPerformed(evt);
        }else if (this.rdCensoPlantacion.isSelected()){
            this.rdCensoPlantacion_Click(evt);
        }
    }//GEN-LAST:event_rdCiclo2ActionPerformed
    
    private void llenarTablaRanking(Map mapa, String temporada, String tipo){
        Map sorted = new TreeMap(invertir(mapa)); Socio unSocio; int puesto = 0;
        Iterator it = sorted.values().iterator(); Vector row; String ciclo;
        ((DefaultTableModel)this.tblListadoRanking.getModel()).setNumRows(0);
        DecimalFormat decimal = new DecimalFormat();
        decimal.setMaximumFractionDigits(2);
        decimal.setMinimumFractionDigits(2);
        while (it.hasNext()){
            unSocio = (Socio)it.next();
            puesto = puesto + 1;
            row = new Vector();
            row.addElement(String.valueOf(puesto));
            row.addElement(String.valueOf(unSocio.getNroSocio()));
            row.addElement(unSocio.getNomApe());
            if (tipo.equals("censo plantacion")){
                if (temporada.equals(" ")){
                    row.addElement((String)decimal.format(unSocio.getRankingCensoPlantacionAll(this.getRdNombreCiclo())));
                }else{
                    row.addElement((String)decimal.format(unSocio.getRankingCensoPlantacion(temporada, this.getRdNombreCiclo())));
                }
            }else if (tipo.equals("censo entrega")){
                if(temporada.equals(" ")){
                    row.addElement((String)decimal.format(unSocio.getRankingCensoEntregaAll(this.getRdNombreCiclo())));
                }else{
                    row.addElement((String)decimal.format(unSocio.getRankingCensoEntrega(temporada, this.getRdNombreCiclo())));
                }
            }else if (tipo.equals("entrega")){
                if (temporada.equals(" ")){
                    row.addElement((String)decimal.format(unSocio.getTotalEntrega(this.getRdNombreCiclo())));
                }else{
                    row.addElement((String)decimal.format(unSocio.getTotalEntrega(temporada, this.getRdNombreCiclo())));
                }
            }
            ((DefaultTableModel)this.tblListadoRanking.getModel()).addRow(row);
            
        }
        
    }
    
    private String getRdNombreCiclo(){
        if (this.rdTodosCiclos.isSelected()){
            return "Todos";
        }else if (this.rdCiclo1.isSelected()){
            return "1 Año";
        }else{
            return "2 Años";
        }
    }
    
    private String getRdNombreReporte(){
        if (this.rdTodosCiclos.isSelected()){
            return "";
        }else if (this.rdCiclo1.isSelected()){
            return "de Mandioca de 1 Año";
        }else{
            return "de Mandionca de 2 Años";
        }
    }
    
    private Map invertir(Map mapa){
        Map sorted = new TreeMap(mapa);
        Map retornar = new HashMap();
        Iterator it = sorted.values().iterator();
        int cont = 0;
        while (it.hasNext()){
            cont = cont + 1;
            it.next();
        }
        it = sorted.values().iterator();
        while (it.hasNext()){
            retornar.put(cont, (Socio)it.next());
            cont = cont - 1;
        }
        return retornar;
    }
    
    private void llenarTabla(Map mapa){
        String temporada = txtTemporada.getText().replace("Temporada ", "");
        double cubierto = (Double)cmbCubierto.getSelectedItem();
        Map sorted = new TreeMap(mapa); Socio unSocio;
        Iterator it = sorted.values().iterator(); Vector row;
        ((DefaultTableModel)this.tblListadoCub.getModel()).setNumRows(0);
        while (it.hasNext()){
            unSocio = (Socio)it.next();
            row = new Vector();
            row.addElement(unSocio.getNroSocio());
            row.addElement(unSocio.getNomApe());
            row.addElement(unSocio.getTotalHec(temporada,cubierto));
            ((DefaultTableModel)this.tblListadoCub.getModel()).addRow(row);
            
        }
    }
    
    
    private void load(){
        String temporada = txtTemporada.getText().replace("Temporada ", "");
        lblTotal1KgP.setText(String.valueOf(new Double(this.emp.getTotal1Hec(temporada)).longValue() +
                " Hectareas " + dcf.format(new Double(this.emp.getTotal1KgCensoP(temporada)).longValue()) + " Kg"));
        lblTotal2kgP.setText(String.valueOf(new Double(this.emp.getTotal2Hec(temporada)).longValue() +
                 " Hectareas " + dcf.format(new Double(this.emp.getTotal2KgCensoP(temporada)).longValue()) + " Kg"));
        lblTotal1kgE.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1KgCensoEntrega(temporada)).longValue()) +
                " Kg " ));
        lblTotal2kgE.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal2KgCensoEntrega(temporada)).longValue()) +
                 " Kg "));
        lblTotalCensoPlantacion.setText(String.valueOf(new Double(this.emp.getTotal1Hec(temporada) +
                this.emp.getTotal2Hec(temporada)).longValue() + " Hectareas " +
                dcf.format(new Double(this.emp.getTotal1KgCensoP(temporada) + this.emp.getTotal2KgCensoP(temporada)).longValue()) +
                " Kg"));
        lblTotalKgCEntrega.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1KgCensoEntrega(temporada) +
                this.emp.getTotal2KgCensoEntrega(temporada)).longValue()) + " Kg"));
        lblTotalEnt1Año.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal1AñoEntrega(temporada)).longValue())) + " Kg");
        lblTotalEnt2Año.setText(String.valueOf(dcf.format(new Double(this.emp.getTotal2AñoEntrega(temporada)).longValue())) + " Kg");
        lblTotalEntrega.setText(String.valueOf(dcf.format(new Double(this.emp.getTotalEntrega(temporada)).longValue())) + " Kg");
        cargarCmbCubierto(this.emp.getCubierto(temporada));
        
        
    }
    
    private void cargarCmbCubierto(List list){
        cmbCubierto.removeAllItems();
        Set set = new TreeSet(list);
        Iterator it = set.iterator();
        while (it.hasNext()){
            cmbCubierto.addItem(it.next());
        }
        if(set.size() == 0){
             ((DefaultTableModel)this.tblListadoCub.getModel()).setNumRows(0);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Estadistica(new Empresa()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total1KgP;
    private javax.swing.JLabel Total1KgP1;
    private javax.swing.JLabel Total1KgP3;
    private javax.swing.JButton bttAbajo;
    private javax.swing.JButton bttAbajo1;
    private javax.swing.JButton bttAceptar;
    private javax.swing.JButton bttArriba;
    private javax.swing.ButtonGroup bttGroupCiclo;
    private javax.swing.ButtonGroup bttGroupRanking;
    private javax.swing.JButton bttListar;
    private javax.swing.JButton bttListar1;
    private javax.swing.JButton bttListarRanking;
    private javax.swing.JCheckBox chkTodos;
    private javax.swing.JComboBox cmbCubierto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPnlRanking;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kg1AñoP;
    private javax.swing.JLabel kg1AñoP1;
    private javax.swing.JLabel lbl1Año;
    private javax.swing.JLabel lbl1Año1;
    private javax.swing.JLabel lbl1Año2;
    private javax.swing.JLabel lbl2Año;
    private javax.swing.JLabel lbl2Año1;
    private javax.swing.JLabel lbl2Año2;
    private javax.swing.JLabel lblCensoPlantacion;
    private javax.swing.JLabel lblCensoPlantacion1;
    private javax.swing.JLabel lblCensoPlantacion2;
    private javax.swing.JLabel lblCubierto;
    private javax.swing.JLabel lblTotal1KgP;
    private javax.swing.JLabel lblTotal1kgE;
    private javax.swing.JLabel lblTotal2kgE;
    private javax.swing.JLabel lblTotal2kgP;
    private javax.swing.JLabel lblTotalCensoPlantacion;
    private javax.swing.JLabel lblTotalEnt1Año;
    private javax.swing.JLabel lblTotalEnt2Año;
    private javax.swing.JLabel lblTotalEntrega;
    private javax.swing.JLabel lblTotalKgCEntrega;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JRadioButton rdCensoEntrega;
    private javax.swing.JRadioButton rdCensoPlantacion;
    private javax.swing.JRadioButton rdCiclo1;
    private javax.swing.JRadioButton rdCiclo2;
    private javax.swing.JRadioButton rdEntrega;
    private javax.swing.JRadioButton rdTodosCiclos;
    private javax.swing.JTable tblListadoCub;
    private javax.swing.JTable tblListadoRanking;
    private javax.swing.JTabbedPane tblPane;
    private javax.swing.JPanel tbpCubierto;
    private javax.swing.JPanel tbpTotales;
    private javax.swing.JTextField txtTemporada;
    // End of variables declaration//GEN-END:variables
    
}
