/*
 * V_Telefono.java
 *
 * Created on 28 de diciembre de 2007, 10:52
 */

package Gui;

import base.Empresa;
import base.Socio;
import base.Telefono;
import db.DbTelefono;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author  Witzkito
 */
public class V_Telefono extends javax.swing.JFrame {
    
    private Empresa empresa;
    private Socio unSocio;
    private JFrame principal;
    /** Creates new form V_Telefono */
    public V_Telefono(Empresa empresa, Socio unSocio, JFrame principal) {
        this.empresa = empresa;
        this.unSocio = unSocio;
        this.principal = principal;
        initComponents();
        load();
         this.setLocationRelativeTo(principal);
    }
    
    public V_Telefono(){}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        txtTelefono = new javax.swing.JFormattedTextField();
        bttAceptar = new javax.swing.JButton();
        txtTelefonoCelular = new javax.swing.JFormattedTextField();
        bttCancelar = new javax.swing.JButton();
        lblCasa = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Telefono");
        setBackground(this.empresa.getOptions().getColor_form());
        setIconImage(this.empresa.getOptions().getIcono().getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windows_closing(evt);
            }
        });

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0####-######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono.setToolTipText("Telefono del Socio");

        bttAceptar.setIcon(new ImageIcon("img/Ok.png"));
        bttAceptar.setText("Aceptar");
        bttAceptar.setToolTipText("Aceptar Telefonos");
        bttAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAceptar_Click(evt);
            }
        });

        try {
            txtTelefonoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0####-15######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefonoCelular.setToolTipText("Telefono del Socio");

        bttCancelar.setIcon(new ImageIcon("img/RedCross.png"));
        bttCancelar.setText("Cancelar");
        bttCancelar.setToolTipText("Cancelar Telefonos");
        bttCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelar_Click(evt);
            }
        });

        lblCasa.setIcon(new ImageIcon("img/Hogar.png"));
        lblCasa.setText("Fijo");

        lblCel.setIcon(new ImageIcon("img/cel.png"));
        lblCel.setText("Celular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCasa)
                            .addComponent(lblCel))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(bttCancelar)))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCasa)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCel)
                    .addComponent(txtTelefonoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttCancelar)
                    .addComponent(bttAceptar))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCancelar_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelar_Click
        this.principal.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_bttCancelar_Click

    private void bttAceptar_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAceptar_Click
       Telefono tel; DbTelefono dbTel = new DbTelefono(Empresa.con);
       tel = new Telefono(Telefono.tipoFijo(), String.valueOf(txtTelefono.getValue()));
       this.unSocio.addTelefono(tel);
       dbTel.borrar(tel, unSocio);
       dbTel.Insert(tel, this.unSocio);
       tel = new Telefono(Telefono.tipoCelular(), String.valueOf(txtTelefonoCelular.getValue()));
       this.unSocio.addTelefono(tel);
       dbTel.borrar(tel, unSocio);
       dbTel.Insert(tel, this.unSocio);
       this.principal.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bttAceptar_Click

    private void windows_closing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windows_closing
        this.principal.setVisible(true);
    }//GEN-LAST:event_windows_closing
    
    private void load(){
        if (unSocio.getTelefono(Telefono.tipoFijo()) != null){
            txtTelefono.setText(unSocio.getTelefono(Telefono.tipoFijo()).getTelefono());
        }
        if (unSocio.getTelefono(Telefono.tipoCelular()) != null){
             txtTelefonoCelular.setText(unSocio.getTelefono(Telefono.tipoCelular()).getTelefono());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Telefono().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAceptar;
    private javax.swing.JButton bttCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCasa;
    private javax.swing.JLabel lblCel;
    private javax.swing.JFormattedTextField txtTelefono;
    private javax.swing.JFormattedTextField txtTelefonoCelular;
    // End of variables declaration//GEN-END:variables
    
}
